# Lunchinga New Bank Branch in Toronto

# Introduction

 A famous Canadian bank manager decided to increase the number of its branch in Toronto. Our mission is to recommend the best neighborhoods for the inauguration of this new bank branch. 

 This problem could be solved by different strategies, but in this project, we will create an indicator to prioritize the best 5 neighborhoods for Launching a new branch of the bank.

 For this purpose our indicator  is defined as follows: 
 

  #### Locating Index= (Population of the Neighborhood)* (Average Income of People living in neighborhood)/(Normalized Bank Availability Index+1)/10^8
  
  
 
 The more the "Locating Index" means a better place to lunch a new bank branch.

# Methodology

Priotrizing neighborhoods for lunching new bank branch would be so challenging. To overcome this challenge it is logical to pursue a suitable methodology. our methodologies steps are as follows:



### 1- Data gathering step:

In this step we search for valid data about Toronto neighborhoods population, Income level, latitude and longitude, bank availibilty. 



### 2- indicator defining for priotorizing new bank branch:

As mentioned in Introduction section our LOCATING INDEX would be as follows:

### Locating Index= (Population of the Neighborhood)* (Average Income of People living in neighborhood)/(Normalized Bank Availability Index+1)/10^8


### 3- calculting indicator for differnet neighborhoods:

In this step we will calculate the LOCATING INDEX for each neighborhoods and sort them and select the top 5 best neighborhoods too lunch new bank branch in Toronto. 


### 4- visulizing result: 

In this step we will visualize the  result by using follium map.

# Data

For solving this problem we will use 4 datasets as follows:

    
    1- "Toronto Neighborhood latitude and longitude" from link below: 
    
    Url="http://cocl.us/Geospatial_data"
    
    
    2- "Toronto Neighborhoods Names" from link below:
    
    Url:"https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
    
    
    3- "Toronto Neighborhoods Population and Income" from link below:
    
    Url:"https://en.wikipedia.org/wiki/Demographics_of_Toronto_neighbourhoods"
    
    
    4- "Toronto venu datasets" which would be fetched from Foursqaure api

In [1]:
import pandas as pd

### 1- "Toronto Neighborhood latitude and longitude"

In this part we download the latitude and longitude of every postal code of Toronto neighborhoods

In [2]:
url2='http://cocl.us/Geospatial_data'
dfs2 = pd.read_csv(url2)
dfs2.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

 ### 2- "Toronto Neighborhoods Names"

In This part we fetch the Toronto neighborhoods names from wikipedia

In [3]:
url1='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
dfs1 = pd.read_html(url1)
dfs1=dfs1[0]
dfs_filter=dfs1[dfs1.Borough !='Not assigned']
dfs_filter.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

### 3- "Toronto Neighborhoods Population and Income"

In this part we fetch the Toronto Neighborhoods Population and Income from wikipedia

In [4]:
url3='https://en.wikipedia.org/wiki/Demographics_of_Toronto_neighbourhoods'
dfs3 = pd.read_html(url3)
dfs3= dfs3[5]
dfs3

,Name,FM,Census Tracts,Population,Land area (km2),Density (people/km2),% Change in Population since 2001,Average Income,Transit Commuting %,% Renters,Second most common language (after English) by name,Second most common language (after English) by percentage,Map
0,Toronto CMA Average,NaN,All,5113149.0,5903.63,866.0,9.0,40704.0,10.6,11.4,NaN,NaN,NaN
1,Agincourt,S,"0377.01, 0377.02, 0377.03, 0377.04, 0378.02, 0...",44577.0,12.45,3580.0,4.6,25750.0,11.1,5.9,Cantonese (19.3%),19.3% Cantonese,NaN
2,Alexandra Park,OCoT,0039.00,4355.0,0.32,13609.0,0.0,19687.0,13.8,28.0,Cantonese (17.9%),17.9% Cantonese,NaN
3,Allenby,OCoT,0140.00,2513.0,0.58,4333.0,-1.0,245592.0,5.2,3.4,Russian (1.4%),01.4% Russian,NaN
4,Amesbury,NY,"0280.00, 0281.01, 0281.02",17318.0,3.51,4934.0,1.1,27546.0,16.4,19.7,Spanish (6.1%),06.1% Spanish,NaN
5,Armour Heights,NY,0298.00,4384.0,2.29,1914.0,2.0,116651.0,10.8,16.1,Russian (9.4%),09.4% Russian,NaN
6,Banbury,NY,0267.00,6641.0,2.72,2442.0,5.0,92319.0,6.1,4.8,Unspecified Chinese (5.1%),05.1% Unspecified Chinese,NaN
7,Bathurst Manor,NY,"0297.01, 0310.01, 0310.02",14945.0,4.69,3187.0,12.3,34169.0,13.4,18.6,Russian (9.5%),09.5% Russian,NaN
8,Bay Street Corridor,OCoT,0062.01,4787.0,0.11,43518.0,3.0,40598.0,17.1,49.3,Mandarin (9.6%),09.6% Mandarin,NaN
9,Bayview Village,NY,"0305.01, 305.02",12280.0,4.14,2966.0,41.6,46752.0,14.4,15.6,Cantonese (8.4%),08.4% Cantonese,NaN
10,Bayview Woods – Steeles,NY,"0323.01, 0323.02, 0324.01",13298.0,4.07,3267.0,-1.5,41485.0,11.2,13.9,Cantonese (9.3%),09.3% Cantonese,NaN
11,Bedford Park,OCoT,"0141.01, 0141.02, 0142.00",13749.0,2.27,6057.0,-1.4,80827.0,15.2,10.1,Greek (0.7%),00.7% Greek,NaN
12,Bendale,S,"0353.02, 0354.00, 0367.02, 0368.00, 0369.00",28945.0,8.49,3409.0,12.9,29723.0,13.0,10.4,Tamil (3.7%),03.7% Tamil,NaN
13,Birch Cliff,S,"0338.00, 0339.00",12266.0,3.48,3525.0,-3.0,48965.0,11.4,15.2,Unspecified Chinese (0.9%),00.9% Unspecified Chinese,NaN
14,Bloor West Village,OCoT,0104.00,5175.0,0.74,6993.0,-2.0,55578.0,20.7,8.3,Ukrainian (3.6%),03.6% Ukrainian,NaN
15,Bracondale Hill,OCoT,0114.00,5343.0,0.62,8618.0,-3.0,41605.0,18.2,24.2,Greek (4.8%),04.8% Greek,NaN
16,Branson,NY,"0309.00, 0317.05",8017.0,1.25,6414.0,-3.8,27156.0,18.0,27.2,Russian (24.1%),24.1% Russian,NaN
17,Bridle Path,NY,0264.00,1540.0,3.46,445.0,11.0,314107.0,7.1,2.3,Cantonese (12.0%),12.0% Cantonese,NaN
18,Brockton,OCoT,"0046.00, 0053.00",9039.0,1.10,8217.0,-9.5,27260.0,22.3,17.3,Portuguese (19.9%),19.9% Portuguese,NaN
19,Cabbagetown,OCoT,"0066.00, 0067.00, 0068.00",11120.0,1.40,7943.0,5.3,50398.0,18.5,29.6,Unspecified Chinese (1.6%),01.6% Unspecified Chinese,NaN
20,Caribou Park,NY,0277.00,4097.0,1.02,4017.0,-2.0,103703.0,8.4,7.6,Tagalog (2.9%),02.9% Tagalog,NaN
21,Carleton Village,OCoT,0108.00,6544.0,0.74,8843.0,-4.0,23301.0,19.0,19.9,Portuguese (17.0%),17.0% Portuguese,NaN
22,Casa Loma,OCoT,0118.00,3597.0,0.67,5369.0,23.0,82203.0,18.1,32.9,Korean (1.8%),01.8% Korean,NaN
23,Chaplin Estates,OCoT,0129.00,4906.0,0.93,5275.0,1.0,81288.0,22.7,24.5,French (1.2%),01.2% French,NaN
24,Christie Pits,OCoT,0094.00,5124.0,0.64,8006.0,-5.0,30556.0,18.8,15.3,Portuguese (11.9%),11.9% Portuguese,NaN
25,Church and Wellesley,OCoT,"0063.01, 0063.02",13397.0,0.55,24358.0,8.8,37653.0,25.1,57.0,Spanish (1.8%),01.8% Spanish,NaN
26,Clairlea,S,"0340.00, 0348.00",11104.0,3.58,3102.0,1.8,33392.0,18.1,12.7,Filipino (4.3%),04.3% Filipino,NaN
27,Cliffcrest,S,"0333.00, 0334.00, 0335.00",14531.0,7.01,2073.0,-2.9,38182.0,12.5,12.2,Tamil (1.5%),01.5% Tamil,NaN
28,Cliffside,S,"0336.00, 0337.00",9386.0,2.45,3831.0,-6.3,32701.0,14.8,11.4,Cantonese (2.3%),02.3% Cantonese,NaN
29,Corktown,OCoT,0016.00,4484.0,0.67,6693.0,77.0,54681.0,15.5,17.6,Spanish (2.1%),02.1% Spanish,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,Sunnylea,E,"0216.00, 0217.00, 0218.00, 0219.00",17602.0,5.23,3366.0,-1.1,51398.0,13.0,17.1,Polish (5.2%),05.2% Polish,NaN
127,Swansea,OCoT,"0050.01, 0050.02",11133.0,3.76,2961.0,0.5,58681.0,18.3,12.8,Polish (3.0%),03.0% Polish,NaN
128,Tam O'Shanter – Sullivan,S,"0374.01, 0374.02, 0374.03, 0375.02, 0375.03, 0...",27235.0,5.44,5006.0,3.4,27717.0,12.2,15.3,Unspecified Chinese (12.6%),12.6% Unspecified Chinese,NaN
129,The Annex,OCoT,"0091.01, 0091.02, 0092.00",15602.0,1.47,10614.0,-2.3,63636.0,22.1,41.9,Spanish (1.3%),01.3% Spanish,NaN
130,The Beaches,OCoT,"0020.00, 0021.00, 0022.00, 0023.00, 0024.00",20416.0,3.57,5719.0,7.8,67536.0,13.8,16.2,Cantonese (0.7%),00.7% Cantonese,NaN
131,The Danforth,OCoT,"83.00, 84.00",7849.0,0.87,9022.0,-1.0,44979.0,23.3,19.0,Greek (7.4%),07.4% Greek,NaN
132,The Elms,E,"0244.01, 0244.02",9437.0,2.86,3300.0,-3.3,28014.0,12.6,13.7,Spanish (6.1%),06.1% Spanish,NaN
133,The Junction,OCoT,"0101.00, 0105.00, 0106.00",11391.0,2.36,4827.0,22.8,34906.0,18.0,17.0,Portuguese (4.1%),04.1% Portuguese,NaN
134,The Kingsway,E,"0226.00, 0227.00, 0228.00, 0229.00",8780.0,2.58,3403.0,7.9,110944.0,11.8,6.2,Ukrainian (1.8%),01.8% Ukrainian,NaN
135,The Queensway,E,0215.00,6207.0,2.62,2369.0,3.0,38944.0,12.9,9.0,Italian (4.1%),04.1% Italian,NaN
136,Thistletown,E,"0250.01, 0250.02, 0250.05",16790.0,3.97,4229.0,1.4,28955.0,11.2,13.7,Punjabi (8.6%),08.6% Punjabi,NaN
137,Toronto Islands,OCoT,0002.00,627.0,3.17,198.0,-5.0,43344.0,18.3,5.6,None (0%),0% any,NaN
138,Trinity–Bellwoods,OCoT,"0040.00, 0043.00",8687.0,0.92,9442.0,-3.1,31106.0,17.7,16.5,Portuguese (13.6%),13.6% Portuguese,NaN
139,Upper Beaches,OCoT,"0025.00, 0077.00, 0078.00, 0079.00",19830.0,2.92,6791.0,0.5,44346.0,18.6,17.4,Cantonese (0.7%),00.7% Cantonese,NaN
140,Victoria Village,NY,"0261.00, 0262.01, 0262.02",17047.0,4.72,3612.0,2.5,29657.0,15.6,23.4,Urdu (3.2%),03.2% Urdu,NaN
141,Wallace Emerson,OCoT,"0097.01, 0097.02",10338.0,0.88,11748.0,-1.8,25029.0,22.8,23.0,Portuguese (19.2%),19.2% Portuguese,NaN
142,West Deane Park,E,0234.00,4395.0,2.13,2063.0,1.0,41582.0,8.3,4.9,Ukrainian (2.3%),02.3% Ukrainian,NaN
143,West Hill,S,"0358.01, 0358.02, 0358.03, 0359.00, 0360.00",25632.0,9.58,2676.0,-4.1,27936.0,14.6,14.7,Tamil (3.0%),03.0% Tamil,NaN
144,West Rouge,S,"0802.01, 0802.02",9300.0,4.45,2090.0,-1.8,44605.0,14.1,0.8,Cantonese (2.8%),02.8% Cantonese,NaN
145,Westminster,NY,"0317.02, 0317.03, 0317.04",16386.0,2.37,6914.0,0.8,27826.0,14.6,23.4,Russian (31.4%),31.4% Russian,NaN
146,Westmount,E,0240.02,5857.0,1.04,5932.0,5.0,35183.0,9.6,23.4,Ukrainian (10.6%),10.6% Ukrainian,NaN
147,Weston,Y,"0175.01, 0175.02, 0176.00",16476.0,2.51,6564.0,-5.6,27446.0,15.5,26.5,Spanish (7.0%),07.0% Spanish,NaN
148,Wexford,S,"0349.00, 0350.00, 0371.00",17844.0,7.97,2239.0,-3.2,28556.0,14.0,15.1,Filipino (4.5%),04.5% Filipino,NaN
149,Willowdale,NY,"0300.00, 0306.01, 0306.02, 0307.02, 0308.01, 0...",43144.0,7.68,5618.0,62.3,39895.0,15.6,12.9,Cantonese (7.9%),07.9% Cantonese,NaN
150,Wilson Heights,NY,"0288.00, 0297.02",13732.0,4.14,3317.0,1.9,37978.0,15.9,18.0,Filipino (6.2%),06.2% Filipino,NaN
151,Woburn,S,"0356.00, 0357.01, 0357.02, 0363.07, 0364.01, 0...",48507.0,13.34,3636.0,-1.5,26190.0,13.3,16.0,Gujarati (9.1%),09.1% Gujarati,NaN
152,Wychwood,OCoT,0116.00,4182.0,0.68,6150.0,-2.0,53613.0,17.1,20.1,Portuguese (2.7%),02.7% Portuguese,NaN
153,York Mills,NY,"0273.01, 0273.02, 0274.01, 0274.02",17564.0,7.29,2409.0,2.0,92099.0,10.0,11.8,Korean (4.0%),04.0% Korean,NaN
154,York University Heights,NY,"0311.02, 0311.03, 0311.04, 0311.05, 0311.06",26140.0,13.21,1979.0,-1.2,24432.0,15.2,20.4,Italian (6.6%),06.6% Italian,NaN
155,Yorkville,OCoT,"0088.00, 0089.00",6045.0,0.56,10795.0,62.6,105239.0,18.3,27.9,French (1.9%),01.9% French,NaN

### 4-"Toronto venu datasets" which would be fetched from Foursqaure api

In this section we will use Foursquar API  to fetch Toronto venu datasets

In [5]:
CLIENT_ID = '1JK4RFP1J5QH2VOIBRJ2VFMWCTXZBB1EEYTCUBYP00LAC5F5' # your Foursquare ID
CLIENT_SECRET = 'FRBYSXFPH1XIBSZNN0QMO3LDSIZYRQ4U2YUZ2EKHTW12TDC2' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 1JK4RFP1J5QH2VOIBRJ2VFMWCTXZBB1EEYTCUBYP00LAC5F5
CLIENT_SECRET:FRBYSXFPH1XIBSZNN0QMO3LDSIZYRQ4U2YUZ2EKHTW12TDC2

In [6]:
dfs_Toronto=pd.merge(dfs_filter, dfs2, how='inner', on='Postal Code')
dfs_Toronto

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
13,M3C,North York,Don Mills,43.725900,-79.340923
14,M4C,East York,Woodbine Heights,43.695344,-79.318389
15,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
16,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
17,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe...",43.643515,-79.577201
18,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
19,M4E,East Toronto,The Beaches,43.676357,-79.293031
20,M5E,Downtown Toronto,Berczy Park,43.644771,-79.373306
21,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512
22,M1G,Scarborough,Woburn,43.770992,-79.216917
23,M4G,East York,Leaside,43.709060,-79.363452
24,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
25,M6G,Downtown Toronto,Christie,43.669542,-79.422564
26,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
27,M2H,North York,Hillcrest Village,43.803762,-79.363452
28,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North",43.754328,-79.442259
29,M4H,East York,Thorncliffe Park,43.705369,-79.349372
...,...,...,...,...,...
73,M4R,Central Toronto,"North Toronto West, Lawrence Park",43.715383,-79.405678
74,M5R,Central Toronto,"The Annex, North Midtown, Yorkville",43.672710,-79.405678
75,M6R,West Toronto,"Parkdale, Roncesvalles",43.648960,-79.456325
76,M7R,Mississauga,Canada Post Gateway Processing Centre,43.636966,-79.615819
77,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
78,M1S,Scarborough,Agincourt,43.794200,-79.262029
79,M4S,Central Toronto,Davisville,43.704324,-79.388790
80,M5S,Downtown Toronto,"University of Toronto, Harbord",43.662696,-79.400049
81,M6S,West Toronto,"Runnymede, Swansea",43.651571,-79.484450
82,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan",43.781638,-79.304302
83,M4T,Central Toronto,"Moore Park, Summerhill East",43.689574,-79.383160
84,M5T,Downtown Toronto,"Kensington Market, Chinatown, Grange Park",43.653206,-79.400049
85,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo...",43.815252,-79.284577
86,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest...",43.686412,-79.400049
87,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
88,M8V,Etobicoke,"New Toronto, Mimico South, Humber Bay Shores",43.605647,-79.501321
89,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
90,M1W,Scarborough,"Steeles West, L'Amoreaux West",43.799525,-79.318389
91,M4W,Downtown Toronto,Rosedale,43.679563,-79.377529
92,M5W,Downtown Toronto,Stn A PO Boxes,43.646435,-79.374846
93,M8W,Etobicoke,"Alderwood, Long Branch",43.602414,-79.543484
94,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054
95,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
96,M4X,Downtown Toronto,"St. James Town, Cabbagetown",43.667967,-79.367675
97,M5X,Downtown Toronto,"First Canadian Place, Underground city",43.648429,-79.382280
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

In [7]:
neighborhood_latitude = dfs_Toronto.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = dfs_Toronto.loc[0, 'Longitude'] # neighborhood longitude value

neighborhood_name = dfs_Toronto.loc[0, 'Neighbourhood'] # neighborhood name

In [8]:
LIMIT = 100 # limit of number of venues returned by Foursquare API


radius = 500 # define radius



# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=1JK4RFP1J5QH2VOIBRJ2VFMWCTXZBB1EEYTCUBYP00LAC5F5&client_secret=FRBYSXFPH1XIBSZNN0QMO3LDSIZYRQ4U2YUZ2EKHTW12TDC2&v=20180605&ll=43.7532586,-79.3296565&radius=500&limit=100'

In [9]:
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

In [10]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5f4fc9977f96f27ce901ac78'},
 'response': {'warning': {'text': "There aren't a lot of results near you. Try something more general, reset your filters, or expand the search area."},
  'headerLocation': 'Parkwoods - Donalda',
  'headerFullLocation': 'Parkwoods - Donalda, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 2,
  'suggestedBounds': {'ne': {'lat': 43.757758604500005,
    'lng': -79.32343823984928},
   'sw': {'lat': 43.7487585955, 'lng': -79.33587476015072}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4e8d9dcdd5fbbbb6b3003c7b',
       'name': 'Brookbanks Park',
       'location': {'address': 'Toronto',
        'lat': 43.751976046055574,
        'lng': -79.33214044722958,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.751976046055574,
          'lng': -79.33214044722958}],
        'distance': 245,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['Toronto', 'Toronto ON', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d163941735',
         'name': 'Park',
         'pluralName': 'Parks',
         'shortName': 'Park',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4e8d9dcdd5fbbbb6b3003c7b-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4cb11e2075ebb60cd1c4caad',
       'name': 'Variety Store',
       'location': {'address': '29 Valley Woods Road',
        'lat': 43.75197441585782,
        'lng': -79.33311418516017,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.75197441585782,
          'lng': -79.33311418516017}],
        'distance': 312,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['29 Valley Woods Road', 'Toronto ON', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d1f9941735',
         'name': 'Food & Drink Shop',
         'pluralName': 'Food & Drink Shops',
         'shortName': 'Food & Drink',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/foodanddrink_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4cb11e2075ebb60cd1c4caad-1'}]}]}}

In [11]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [12]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

              name         categories        lat        lng
0  Brookbanks Park               Park  43.751976 -79.332140
1    Variety Store  Food & Drink Shop  43.751974 -79.333114

In [13]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
    # return only relevant information for each nearby venue
    
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [14]:
TORONTO_venues = getNearbyVenues(names=dfs_Toronto['Neighbourhood'],
                                   latitudes=dfs_Toronto['Latitude'],
                                   longitudes=dfs_Toronto['Longitude']
                                  )

Parkwoods
Victoria Village
Regent Park, Harbourfront
Lawrence Manor, Lawrence Heights
Queen's Park, Ontario Provincial Government
Islington Avenue, Humber Valley Village
Malvern, Rouge
Don Mills
Parkview Hill, Woodbine Gardens
Garden District, Ryerson
Glencairn
West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale
Rouge Hill, Port Union, Highland Creek
Don Mills
Woodbine Heights
St. James Town
Humewood-Cedarvale
Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood
Guildwood, Morningside, West Hill
The Beaches
Berczy Park
Caledonia-Fairbanks
Woburn
Leaside
Central Bay Street
Christie
Cedarbrae
Hillcrest Village
Bathurst Manor, Wilson Heights, Downsview North
Thorncliffe Park
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Scarborough Village
Fairview, Henry Farm, Oriole
Northwood Park, York University
East Toronto, Broadview North (Old East York)
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
Kennedy Park, Ionview, East Birchmount Park
Bayview Village
Downsview
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
Golden Mile, Clairlea, Oakridge
York Mills, Silver Hills
Downsview
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
North Park, Maple Leaf Park, Upwood Park
Humber Summit
Cliffside, Cliffcrest, Scarborough Village West
Willowdale, Newtonbrook
Downsview
Studio District
Bedford Park, Lawrence Manor East
Del Ray, Mount Dennis, Keelsdale and Silverthorn
Humberlea, Emery
Birch Cliff, Cliffside West
Willowdale, Willowdale East
Downsview
Lawrence Park
Roselawn
Runnymede, The Junction North
Weston
Dorset Park, Wexford Heights, Scarborough Town Centre
York Mills West
Davisville North
Forest Hill North & West, Forest Hill Road Park
High Park, The Junction South
Westmount
Wexford, Maryvale
Willowdale, Willowdale West
North Toronto West, Lawrence Park
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Canada Post Gateway Processing Centre
Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens
Agincourt
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Clarks Corners, Tam O'Shanter, Sullivan
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Milliken, Agincourt North, Steeles East, L'Amoreaux East
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
New Toronto, Mimico South, Humber Bay Shores
South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens
Steeles West, L'Amoreaux West
Rosedale
Stn A PO Boxes
Alderwood, Long Branch
Northwest, West Humber - Clairville
Upper Rouge
St. James Town, Cabbagetown
First Canadian Place, Underground city
The Kingsway, Montgomery Road, Old Mill North
Church and Wellesley
Business reply mail Processing Centre, South Central Letter Processing Plant Toronto
Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East
Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West

In [15]:
# one hot encoding
Toronto_onehot = pd.get_dummies(TORONTO_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
Toronto_onehot['Neighborhood'] = TORONTO_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [Toronto_onehot.columns[-1]] + list(Toronto_onehot.columns[:-1])
Toronto_onehot = Toronto_onehot[fixed_columns]

Toronto_onehot.head()

,Yoga Studio,Accessories Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,...,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wine Shop,Wings Joint,Women's Store
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Hint: As we just need bank availibilty index, we would filter the above table by "Bank" column.

In [16]:
Toronto_grouped = Toronto_onehot.groupby('Neighborhood').mean().reset_index()
Toronto_grouped_Bank=Toronto_grouped[['Neighborhood','Bank']]
Toronto_grouped_Bank

                                         Neighborhood      Bank
0                                           Agincourt  0.000000
1                              Alderwood, Long Branch  0.000000
2     Bathurst Manor, Wilson Heights, Downsview North  0.095238
3                                     Bayview Village  0.250000
4                   Bedford Park, Lawrence Manor East  0.000000
5                                         Berczy Park  0.000000
6                         Birch Cliff, Cliffside West  0.000000
7        Brockton, Parkdale Village, Exhibition Place  0.000000
8   Business reply mail Processing Centre, South C...  0.000000
9   CN Tower, King and Spadina, Railway Lands, Har...  0.000000
10                                Caledonia-Fairbanks  0.000000
11              Canada Post Gateway Processing Centre  0.000000
12                                          Cedarbrae  0.125000
13                                 Central Bay Street  0.000000
14                                           Christie  0.000000
15                               Church and Wellesley  0.000000
16            Clarks Corners, Tam O'Shanter, Sullivan  0.083333
17    Cliffside, Cliffcrest, Scarborough Village West  0.000000
18                     Commerce Court, Victoria Hotel  0.000000
19                                         Davisville  0.000000
20                                   Davisville North  0.000000
21   Del Ray, Mount Dennis, Keelsdale and Silverthorn  0.000000
22                                          Don Mills  0.000000
23  Dorset Park, Wexford Heights, Scarborough Town...  0.000000
24                                          Downsview  0.066667
25                       Dufferin, Dovercourt Village  0.058824
26      East Toronto, Broadview North (Old East York)  0.000000
27  Eringate, Bloordale Gardens, Old Burnhamthorpe...  0.000000
28                       Fairview, Henry Farm, Oriole  0.030303
29             First Canadian Place, Underground city  0.000000
..                                                ...       ...
65                                           Rosedale  0.000000
66                                           Roselawn  0.000000
67             Rouge Hill, Port Union, Highland Creek  0.000000
68                                 Runnymede, Swansea  0.027778
69                      Runnymede, The Junction North  0.000000
70                                Scarborough Village  0.000000
71  South Steeles, Silverstone, Humbergate, Jamest...  0.000000
72                                     St. James Town  0.000000
73                        St. James Town, Cabbagetown  0.022222
74                      Steeles West, L'Amoreaux West  0.076923
75                                     Stn A PO Boxes  0.000000
76                                    Studio District  0.025000
77  Summerhill West, Rathnelly, South Hill, Forest...  0.062500
78                The Annex, North Midtown, Yorkville  0.000000
79                                        The Beaches  0.000000
80                       The Danforth West, Riverdale  0.000000
81      The Kingsway, Montgomery Road, Old Mill North  0.000000
82                                   Thorncliffe Park  0.045455
83           Toronto Dominion Centre, Design Exchange  0.000000
84                     University of Toronto, Harbord  0.029412
85                                   Victoria Village  0.000000
86                                          Westmount  0.000000
87                                             Weston  0.000000
88                                  Wexford, Maryvale  0.000000
89                            Willowdale, Newtonbrook  0.000000
90                        Willowdale, Willowdale East  0.000000
91                        Willowdale, Willowdale West  0.200000
92                                             Woburn  0.000000
93                                   Woodbine Heights  0.000000
94                                    York Mills West  0.000000

[95 rows x 2 columns]

Then we calculate "Bank index" by adding 1 to "Bank" column. The aim of this process is to avoid infinity result in the case of zero "Bank" number.

In [17]:
Toronto_grouped_Bank['Bank index']=Toronto_grouped_Bank.Bank+1
Toronto_grouped_Bank

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

                                         Neighborhood      Bank  Bank index
0                                           Agincourt  0.000000    1.000000
1                              Alderwood, Long Branch  0.000000    1.000000
2     Bathurst Manor, Wilson Heights, Downsview North  0.095238    1.095238
3                                     Bayview Village  0.250000    1.250000
4                   Bedford Park, Lawrence Manor East  0.000000    1.000000
5                                         Berczy Park  0.000000    1.000000
6                         Birch Cliff, Cliffside West  0.000000    1.000000
7        Brockton, Parkdale Village, Exhibition Place  0.000000    1.000000
8   Business reply mail Processing Centre, South C...  0.000000    1.000000
9   CN Tower, King and Spadina, Railway Lands, Har...  0.000000    1.000000
10                                Caledonia-Fairbanks  0.000000    1.000000
11              Canada Post Gateway Processing Centre  0.000000    1.000000
12                                          Cedarbrae  0.125000    1.125000
13                                 Central Bay Street  0.000000    1.000000
14                                           Christie  0.000000    1.000000
15                               Church and Wellesley  0.000000    1.000000
16            Clarks Corners, Tam O'Shanter, Sullivan  0.083333    1.083333
17    Cliffside, Cliffcrest, Scarborough Village West  0.000000    1.000000
18                     Commerce Court, Victoria Hotel  0.000000    1.000000
19                                         Davisville  0.000000    1.000000
20                                   Davisville North  0.000000    1.000000
21   Del Ray, Mount Dennis, Keelsdale and Silverthorn  0.000000    1.000000
22                                          Don Mills  0.000000    1.000000
23  Dorset Park, Wexford Heights, Scarborough Town...  0.000000    1.000000
24                                          Downsview  0.066667    1.066667
25                       Dufferin, Dovercourt Village  0.058824    1.058824
26      East Toronto, Broadview North (Old East York)  0.000000    1.000000
27  Eringate, Bloordale Gardens, Old Burnhamthorpe...  0.000000    1.000000
28                       Fairview, Henry Farm, Oriole  0.030303    1.030303
29             First Canadian Place, Underground city  0.000000    1.000000
..                                                ...       ...         ...
65                                           Rosedale  0.000000    1.000000
66                                           Roselawn  0.000000    1.000000
67             Rouge Hill, Port Union, Highland Creek  0.000000    1.000000
68                                 Runnymede, Swansea  0.027778    1.027778
69                      Runnymede, The Junction North  0.000000    1.000000
70                                Scarborough Village  0.000000    1.000000
71  South Steeles, Silverstone, Humbergate, Jamest...  0.000000    1.000000
72                                     St. James Town  0.000000    1.000000
73                        St. James Town, Cabbagetown  0.022222    1.022222
74                      Steeles West, L'Amoreaux West  0.076923    1.076923
75                                     Stn A PO Boxes  0.000000    1.000000
76                                    Studio District  0.025000    1.025000
77  Summerhill West, Rathnelly, South Hill, Forest...  0.062500    1.062500
78                The Annex, North Midtown, Yorkville  0.000000    1.000000
79                                        The Beaches  0.000000    1.000000
80                       The Danforth West, Riverdale  0.000000    1.000000
81      The Kingsway, Montgomery Road, Old Mill North  0.000000    1.000000
82                                   Thorncliffe Park  0.045455    1.045455
83           Toronto Dominion Centre, Design Exchange  0.000000    1.000000
84                     University of Toronto, Harbord  0.029412    1.029412
85                                   Victoria Village  0.000000    1.000000
86                                          Westmount  0.000000    1.000000
87                                             Weston  0.000000    1.000000
88                                  Wexford, Maryvale  0.000000    1.000000
89                            Willowdale, Newtonbrook  0.000000    1.000000
90                        Willowdale, Willowdale East  0.000000    1.000000
91                        Willowdale, Willowdale West  0.200000    1.200000
92                                             Woburn  0.000000    1.000000
93                                   Woodbine Heights  0.000000    1.000000
94                                    York Mills West  0.000000    1.000000

[95 rows x 3 columns]

Now it is timme to merge to tables to calcalate locating index.

In [18]:
merge_result=pd.merge(Toronto_grouped_Bank,dfs3, left_on='Neighborhood', right_on='Name', how='inner')
merge_result

,Neighborhood,Bank,Bank index,Name,FM,Census Tracts,Population,Land area (km2),Density (people/km2),% Change in Population since 2001,Average Income,Transit Commuting %,% Renters,Second most common language (after English) by name,Second most common language (after English) by percentage,Map
0,Agincourt,0.000000,1.000000,Agincourt,S,"0377.01, 0377.02, 0377.03, 0377.04, 0378.02, 0...",44577.0,12.45,3580.0,4.6,25750.0,11.1,5.9,Cantonese (19.3%),19.3% Cantonese,NaN
1,Bayview Village,0.250000,1.250000,Bayview Village,NY,"0305.01, 305.02",12280.0,4.14,2966.0,41.6,46752.0,14.4,15.6,Cantonese (8.4%),08.4% Cantonese,NaN
2,Church and Wellesley,0.000000,1.000000,Church and Wellesley,OCoT,"0063.01, 0063.02",13397.0,0.55,24358.0,8.8,37653.0,25.1,57.0,Spanish (1.8%),01.8% Spanish,NaN
3,Davisville,0.000000,1.000000,Davisville,OCoT,"0126.00, 0127.00, 0128.02, 0128.03, 0128.04",23727.0,3.14,7556.0,4.5,55735.0,26.0,31.7,Persian (1.5%),01.5% Persian,NaN
4,Don Mills,0.000000,1.000000,Don Mills,NY,"0263.02, 0263.03, 0263.04, 0268.00, 0269.02",21372.0,8.99,2377.0,11.9,47515.0,10.8,18.6,Unspecified Chinese (3.9%),03.9% Unspecified Chinese,NaN
5,Downsview,0.066667,1.066667,Downsview,NY,"0289.00, 0290.00, 0291.01, 0291.02, 0292.00, 0...",36613.0,16.13,2270.0,-5.0,26751.0,14.4,18.3,Italian (11.7%),11.7% Italian,NaN
6,Humber Summit,0.000000,1.000000,Humber Summit,NY,"0315.01, 0315.02, 0315.03",12766.0,7.89,1618.0,2.1,26117.0,7.3,7.6,Italian (15.1%),15.1% Italian,NaN
7,Lawrence Park,0.000000,1.000000,Lawrence Park,OCoT,"0138.00, 0265.00",6653.0,3.64,1828.0,-5.1,214110.0,8.3,4.6,French (0.8%),00.8% French,NaN
8,Parkwoods,0.000000,1.000000,Parkwoods,NY,"0270.01, 0270.02, 0271.01, 0271.02, 0272.01, 0...",26533.0,4.96,5349.0,-3.7,34811.0,14.0,22.5,Unspecified Chinese (3.4%),03.4% Unspecified Chinese,NaN
9,Rosedale,0.000000,1.000000,Rosedale,OCoT,"0086.00, 0087.00",7672.0,2.72,2821.0,4.8,213941.0,11.3,11.9,Unspecified Chinese (1.0%),01.0% Unspecified Chinese,NaN
10,Scarborough Village,0.000000,1.000000,Scarborough Village,S,"0331.03, 0332.00",12796.0,2.03,6303.0,-9.0,24413.0,16.2,22.0,Tamil (11.4%),11.4% Tamil,NaN
11,St. James Town,0.000000,1.000000,St. James Town,OCoT,0065.00,14666.0,0.23,63765.0,-10.0,22341.0,27.4,46.2,Filipino (8.1%),08.1% Filipino,NaN
12,The Beaches,0.000000,1.000000,The Beaches,OCoT,"0020.00, 0021.00, 0022.00, 0023.00, 0024.00",20416.0,3.57,5719.0,7.8,67536.0,13.8,16.2,Cantonese (0.7%),00.7% Cantonese,NaN
13,Victoria Village,0.000000,1.000000,Victoria Village,NY,"0261.00, 0262.01, 0262.02",17047.0,4.72,3612.0,2.5,29657.0,15.6,23.4,Urdu (3.2%),03.2% Urdu,NaN
14,Westmount,0.000000,1.000000,Westmount,E,0240.02,5857.0,1.04,5932.0,5.0,35183.0,9.6,23.4,Ukrainian (10.6%),10.6% Ukrainian,NaN
15,Weston,0.000000,1.000000,Weston,Y,"0175.01, 0175.02, 0176.00",16476.0,2.51,6564.0,-5.6,27446.0,15.5,26.5,Spanish (7.0%),07.0% Spanish,NaN
16,Woburn,0.000000,1.000000,Woburn,S,"0356.00, 0357.01, 0357.02, 0363.07, 0364.01, 0...",48507.0,13.34,3636.0,-1.5,26190.0,13.3,16.0,Gujarati (9.1%),09.1% Gujarati,NaN

Then we would like to filter our necessary column for better calculation.

In [19]:
select_column=merge_result[['Neighborhood','Bank index','Population','Average Income']]
select_column

            Neighborhood  Bank index  Population  Average Income
0              Agincourt    1.000000     44577.0         25750.0
1        Bayview Village    1.250000     12280.0         46752.0
2   Church and Wellesley    1.000000     13397.0         37653.0
3             Davisville    1.000000     23727.0         55735.0
4              Don Mills    1.000000     21372.0         47515.0
5              Downsview    1.066667     36613.0         26751.0
6          Humber Summit    1.000000     12766.0         26117.0
7          Lawrence Park    1.000000      6653.0        214110.0
8              Parkwoods    1.000000     26533.0         34811.0
9               Rosedale    1.000000      7672.0        213941.0
10   Scarborough Village    1.000000     12796.0         24413.0
11        St. James Town    1.000000     14666.0         22341.0
12           The Beaches    1.000000     20416.0         67536.0
13      Victoria Village    1.000000     17047.0         29657.0
14             Westmount    1.000000      5857.0         35183.0
15                Weston    1.000000     16476.0         27446.0
16                Woburn    1.000000     48507.0         26190.0

In this section we calculate Lacating index and then sort values. as mentioned before " the more the locating index, the better place for lunching new bank branch"

In [20]:
select_column['Locating Index']= ((select_column.Population)*(select_column['Average Income']))/(select_column['Bank index'])/100000000
priority_table=select_column.sort_values(by=['Locating Index'], ascending=True)
priority_table

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,Neighborhood,Bank index,Population,Average Income,Locating Index
14,Westmount,1.000000,5857.0,35183.0,2.060668
10,Scarborough Village,1.000000,12796.0,24413.0,3.123887
11,St. James Town,1.000000,14666.0,22341.0,3.276531
6,Humber Summit,1.000000,12766.0,26117.0,3.334096
15,Weston,1.000000,16476.0,27446.0,4.522003
1,Bayview Village,1.250000,12280.0,46752.0,4.592916
2,Church and Wellesley,1.000000,13397.0,37653.0,5.044372
13,Victoria Village,1.000000,17047.0,29657.0,5.055629
5,Downsview,1.066667,36613.0,26751.0,9.182197
8,Parkwoods,1.000000,26533.0,34811.0,9.236403
4,Don Mills,1.000000,21372.0,47515.0,10.154906
0,Agincourt,1.000000,44577.0,25750.0,11.478578
16,Woburn,1.000000,48507.0,26190.0,12.703983
3,Davisville,1.000000,23727.0,55735.0,13.224243
12,The Beaches,1.000000,20416.0,67536.0,13.788150
7,Lawrence Park,1.000000,6653.0,214110.0,14.244738
9,Rosedale,1.000000,7672.0,213941.0,16.413554

In [21]:
merge_result2=pd.merge(dfs_Toronto,priority_table, left_on='Neighbourhood', right_on='Neighborhood', how='right')
merge_result2

,Postal Code,Borough,Neighbourhood,Latitude,Longitude,Neighborhood,Bank index,Population,Average Income,Locating Index
0,M3A,North York,Parkwoods,43.753259,-79.329656,Parkwoods,1.000000,26533.0,34811.0,9.236403
1,M4A,North York,Victoria Village,43.725882,-79.315572,Victoria Village,1.000000,17047.0,29657.0,5.055629
2,M3B,North York,Don Mills,43.745906,-79.352188,Don Mills,1.000000,21372.0,47515.0,10.154906
3,M3C,North York,Don Mills,43.725900,-79.340923,Don Mills,1.000000,21372.0,47515.0,10.154906
4,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418,St. James Town,1.000000,14666.0,22341.0,3.276531
5,M4E,East Toronto,The Beaches,43.676357,-79.293031,The Beaches,1.000000,20416.0,67536.0,13.788150
6,M1G,Scarborough,Woburn,43.770992,-79.216917,Woburn,1.000000,48507.0,26190.0,12.703983
7,M1J,Scarborough,Scarborough Village,43.744734,-79.239476,Scarborough Village,1.000000,12796.0,24413.0,3.123887
8,M2K,North York,Bayview Village,43.786947,-79.385975,Bayview Village,1.250000,12280.0,46752.0,4.592916
9,M3K,North York,Downsview,43.737473,-79.464763,Downsview,1.066667,36613.0,26751.0,9.182197
10,M3L,North York,Downsview,43.739015,-79.506944,Downsview,1.066667,36613.0,26751.0,9.182197
11,M3M,North York,Downsview,43.728496,-79.495697,Downsview,1.066667,36613.0,26751.0,9.182197
12,M3N,North York,Downsview,43.761631,-79.520999,Downsview,1.066667,36613.0,26751.0,9.182197
13,M9L,North York,Humber Summit,43.756303,-79.565963,Humber Summit,1.000000,12766.0,26117.0,3.334096
14,M4N,Central Toronto,Lawrence Park,43.728020,-79.388790,Lawrence Park,1.000000,6653.0,214110.0,14.244738
15,M9N,York,Weston,43.706876,-79.518188,Weston,1.000000,16476.0,27446.0,4.522003
16,M9P,Etobicoke,Westmount,43.696319,-79.532242,Westmount,1.000000,5857.0,35183.0,2.060668
17,M1S,Scarborough,Agincourt,43.794200,-79.262029,Agincourt,1.000000,44577.0,25750.0,11.478578
18,M4S,Central Toronto,Davisville,43.704324,-79.388790,Davisville,1.000000,23727.0,55735.0,13.224243
19,M4W,Downtown Toronto,Rosedale,43.679563,-79.377529,Rosedale,1.000000,7672.0,213941.0,16.413554
20,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160,Church and Wellesley,1.000000,13397.0,37653.0,5.044372

In [22]:
select_column2=merge_result2[['Neighborhood','Locating Index','Latitude','Longitude']]
select_column3=select_column2.sort_values(by=['Locating Index'], ascending=False)
select_column3

            Neighborhood  Locating Index   Latitude  Longitude
19              Rosedale       16.413554  43.679563 -79.377529
14         Lawrence Park       14.244738  43.728020 -79.388790
5            The Beaches       13.788150  43.676357 -79.293031
18            Davisville       13.224243  43.704324 -79.388790
6                 Woburn       12.703983  43.770992 -79.216917
17             Agincourt       11.478578  43.794200 -79.262029
2              Don Mills       10.154906  43.745906 -79.352188
3              Don Mills       10.154906  43.725900 -79.340923
0              Parkwoods        9.236403  43.753259 -79.329656
11             Downsview        9.182197  43.728496 -79.495697
12             Downsview        9.182197  43.761631 -79.520999
10             Downsview        9.182197  43.739015 -79.506944
9              Downsview        9.182197  43.737473 -79.464763
1       Victoria Village        5.055629  43.725882 -79.315572
20  Church and Wellesley        5.044372  43.665860 -79.383160
8        Bayview Village        4.592916  43.786947 -79.385975
15                Weston        4.522003  43.706876 -79.518188
13         Humber Summit        3.334096  43.756303 -79.565963
4         St. James Town        3.276531  43.651494 -79.375418
7    Scarborough Village        3.123887  43.744734 -79.239476
16             Westmount        2.060668  43.696319 -79.532242

# Result Visualization

In this section we will visualize the top 5 best neighborhooods to lunch new bank branch. for this purpose we use follium library.

In [23]:
!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    folium-0.5.0               |             py_0          45 KB  conda-forge
    openssl-1.1.1g             |       h516909a_1         2.1 MB  conda-forge
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    certifi-2020.6.20          |   py36h9f0ad1d_0         151 KB  conda-forge
    ca-certificates-2020.6.20  |       hecda079_0         145 KB  conda-forge
    branca-0.4.1               |             py_0          26 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

    altair:          4.1.0-py_1        conda-forge
    branca:          0.4.1-py_0        conda-forge
    folium:          0.5.0-py_0        conda-forge
    python_abi:      3.6-1_cp36m       conda-forge
    vincent:         0.4.4-py_1        conda-forge

The following packages will be UPDATED:

    certifi:         2020.6.20-py36_0              --> 2020.6.20-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0             --> 1.1.1g-h516909a_1        conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2020.6.24-0                   --> 2020.6.20-hecda079_0     conda-forge


Downloading and Extracting Packages
folium-0.5.0         | 45 KB     | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
certifi-2020.6.20    | 151 KB    | ##################################### | 100%
ca-certificates-2020 | 145 KB    | ##################################### | 100%
branca-0.4.1         | 26 KB     | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

#### The top 5 best neighborhoods to lunch new bank branch is ordered by locating index in select_column4

In [24]:
select_column4=select_column3.head()
select_column4

     Neighborhood  Locating Index   Latitude  Longitude
19       Rosedale       16.413554  43.679563 -79.377529
14  Lawrence Park       14.244738  43.728020 -79.388790
5     The Beaches       13.788150  43.676357 -79.293031
18     Davisville       13.224243  43.704324 -79.388790
6          Woburn       12.703983  43.770992 -79.216917

In [40]:
# create map of TORONTO using latitude and longitude values
map_TORONTO = folium.Map(location=[43.753259, -79.329656], zoom_start=11)

# add markers to map
for lat, lng, Neighbourhood, index in zip(select_column4['Latitude'], select_column4['Longitude'], select_column4['Neighborhood'],select_column4['Locating Index']):
    label = '{}'.format(Neighbourhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=(1.22)**(index) ,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_TORONTO)  
    
map_TORONTO

In [ ]:
The size of bubbles shows the priortory.

# Discussion

Creating a suitable indicator to choose the best neighborhoods for lunching new bank branch, based on the below principle:


"the more rich and populated neighborhood wwould need more bank branches". 



this principle would be correct generally but in some cases like lack of population or income data. it would be useless. but fortunatedly we had accessed to enough mount of information to calculate this indicator.

# Conclusion

From this Project it is crystal clear that we could utilize lots of perspective to solve this problem, but in my view creating indicator and priotrize neigborrhoods based on would be the suitable one. 


In this project we introduce top 5 best neighborhoods to lunch new bank branch, but the bank manager should also search for the best positons in the mentioned neighborhooods. for example an average place in the first recommended neighborhood (Rosedale) would be less attractive than an exellent place in the third recommended neighborhood (The Beaches). 


the top 5 neighborhoods to lunch new bank branch would be as follows:

In [26]:
select_column4

     Neighborhood  Locating Index   Latitude  Longitude
19       Rosedale       16.413554  43.679563 -79.377529
14  Lawrence Park       14.244738  43.728020 -79.388790
5     The Beaches       13.788150  43.676357 -79.293031
18     Davisville       13.224243  43.704324 -79.388790
6          Woburn       12.703983  43.770992 -79.216917